### ISSUE TITLE
Gráfico de tarta por candidato

### ISSUE THREAD

**Issue by JJ** [elecciones-ugr/elecciones-ugr.github.io#4]
Con sectores que representen cada sector en el total. Por ejemplo, si un candidato tiene 52%, tendrá 10% de profesores, 15% de no sé qué... los datos se procesan en [`charts.js`](js/charts.js)

**Comment by iblancasa** [comment]
Eso, ¿sobre el que hay o sobre uno nuevo subdividiéndolo?

**Comment by JJ** [comment]
Uno nuevo o una página nueva, lo que veas mejor.

El 23 de mayo de 2015, 18:56, Israel Blancas <notifications@github.com>
escribió:

> Eso, ¿sobre el que hay o sobre uno nuevo subdividiéndolo?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elecciones-ugr/elecciones-ugr.github.io/issues/4#issuecomment-104924109>
> .
>



-- 
JJ

**Comment by JJ** [comment]
¿Ya habéis acabado la graduación?

**Comment by iblancasa** [comment]
@JJ fue esta mañana. 

Una cosilla. ¿Habéis hecho esto ya? Es que estoy mirando y debajo del gráfico "gordo" están ya mostrándose estos datos

**Comment by JJ** [comment]
Si pero seria verlos de otra forma para ver como influye cada sector en
cada candidato

El sábado, 23 de mayo de 2015, Israel Blancas <notifications@github.com>
escribió:
> @JJ fue esta mañana.
>
> Una cosilla. ¿Habéis hecho esto ya? Es que estoy mirando y debajo del
gráfico "gordo" están ya mostrándose estos datos
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci4.googleusercontent.com/proxy/Tvijh8IMO8Gf7kGt0dCQTpoCIYIHutUsJkCuUxHmaQWQVM7F-AcVN1wMh57pycogOTucadaf16B2RZl-J7pYSBIzS733GeG-HgFeXDpuXTxaEniOrhqvVHaEZgp7VNAAJqC4qOq9xvHhqFlE_HoKOMgVh0fmdQ=s0-d-e1-ft#https://github.com/notifications/beacon/AAAB9FGGxlFJRv6UEmMWbQPwJV8t8mCAks5oMMYjgaJpZM4EmGaq.gif
>

-- 
JJ

**Comment by Makova** [comment]
¿El color tenue "<style=opacity:0.3176;"> dónde aparecen los gráficos se tiene que quedar así por algo?.

**Comment by JJ** [comment]
Porcentaje de escrutinio

El sábado, 23 de mayo de 2015, Manu <notifications@github.com> escribió:
> ¿El color tenue " dónde aparecen los gráficos se tiene que quedar así por
algo?.
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci5.googleusercontent.com/proxy/qySEz0y0bTB_LUkHbtmZM9xibiS58i--AEMv4tlCppl4-b652V-Sz5f8-A2TBlLh-vB6B0gQqvZhDaoUyxLIrV8G8I2BW-bgFEnEO8Wcz0w6leULFDzHYfzBddTenZuL96gMQZQSb7mudP92Ur2kwnwfKOuyYw=s0-d-e1-ft#https://github.com/notifications/beacon/AAAB9B3MhHfbpqgi9S_aIf5uYbKq9E6qks5oMN7egaJpZM4EmGaq.gif
>

-- 
JJ

**Comment by Makova** [comment]
Sí.

--
Makova

**Comment by JJ** [comment]
Me refiero a que la opacidad corresponde al porcentaje de escrutinio.
Cuando esté al 100%, se verá opaco del todo. Al 3%, apenas se verá.

**Comment by Makova** [comment]
Entendido :ok_hand:

**Comment by Makova** [comment]
¿Cerramos este issue?.
