### ISSUE TITLE
¿Alguien se atreve a convertirlo en un app?

### ISSUE THREAD

**Issue by JJ** [elecciones-ugr/elecciones-ugr.github.io#5]
¿Se podría con Apache Cordova?

**Comment by iblancasa** [comment]
Se puede. Es bastante fácil (más siendo solo un HTML y unos JS)

**Comment by iblancasa** [comment]
Al crear los archivos para "generar la app" hay una carpeta donde se meten los ficheros HTML, JSON, etc... que queremos que se usen...
Habría que copiar los ficheros a esa carpeta cada vez que haya que actualizar (o directamente trabajar con ellos ahí).

Otra cosa que se me ocurre es crear un nuevo repo y añadir este como submódulo del otro (eso sí, la carpeta debe llamarse "www" y no sé si hay algún problema al hacer eso)

**Comment by JJ** [comment]
Me parece una buena idea

El sábado, 23 de mayo de 2015, Israel Blancas <notifications@github.com>
escribió:
> Al crear los archivos para "generar la app" hay una carpeta donde se
meten los ficheros HTML, JSON, etc... que queremos que se usen...
> Habría que copiar los ficheros a esa carpeta cada vez que haya que
actualizar (o directamente trabajar con ellos ahí).
>
> Otra cosa que se me ocurre es crear un nuevo repo y añadir este como
submódulo del otro (eso sí, la carpeta debe llamarse "www" y no sé si hay
algún problema al hacer eso)
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci4.googleusercontent.com/proxy/KvdQ_HUpx-oLAvUgylJlACIk0ETQBul5s6Va0ov9ZUPtz8wRfVOvgalgK_7SZSOhQQ6Pq3X-KAAi7GKxI3vl033LiHl6FDpBjPMOUqWg3cxGg3R0QAfLyiFZ4Cyvdjq_mDdw5qPSTFqzyBZ5nXRNTOIKBxPgWg=s0-d-e1-ft#https://github.com/notifications/beacon/AAAB9CFefIn8qVIt_xIfYupqUcANnqeeks5oMMqagaJpZM4EmjFf.gif
>

-- 
JJ

**Comment by iblancasa** [comment]
[Yo ya he conseguido ejecutarlo](https://github.com/elecciones-ugr/app)

**Comment by Makova** [comment]
Cerramos.

**Comment by JJ** [comment]
El cerrador que cierre... no descartemos que haya que abrirlos de nuevo...

2015-05-27 19:11 GMT+02:00 Manu <notifications@github.com>:

> Cerramos.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elecciones-ugr/elecciones-ugr.github.io/issues/5#issuecomment-106000413>
> .
>



-- 
JJ
