### ISSUE TITLE
No funciona con el jsonp externo

### ISSUE THREAD

**Issue by JJ** [elecciones-ugr/elecciones-ugr.github.io#6]
Da un error porque se niega a ejecutarlo como script en algunos navegadores https://github.com/elecciones-ugr/elecciones-ugr.github.io/commit/7ad27c0ce42f03c8da81274bcc65a1e93d5fc0ca

**Comment by JJ** [comment]
@iblancasa usan el header "nosniff" https://github.com/blog/1482- ¿No se podría poner como estaba al principio? Por lo pronto lo resuelvo así. ¿Puedes hacer una rama en el app que ponga la dirección como quieras?

**Comment by iblancasa** [comment]
No sé. Si toco los submódulos...
Si lo tuviéramos en una gh-pages no creo que falle. Lo raro es que la de
Manuel tiene la modificación y a mí me coge los datos

**Comment by JJ** [comment]
No lo sé, Israel. El problema es que así no funciona. Hay que cambiar el
código totalmente, metiendo peticiones Ajax y demás.
Puedes hacer un gruntfile para que se cambie esa línea cuando se compile,
por ejemplo...

**Comment by iblancasa** [comment]
¿Y usando la API? Sin claves, claro

**Comment by Makova** [comment]
Mejor lo de crear una rama en app.

El 26 de mayo de 2015, 17:53, Israel Blancas <notifications@github.com>
escribió:

> ¿Y usando la API? Sin claves, claro
> El 26/5/2015 17:45, "Israel Blancas" <iblancasa@gmail.com> escribió:
>
> > No sé. Si toco los submódulos...
> > Si lo tuviéramos en una gh-pages no creo que falle. Lo raro es que la de
> > Manuel tiene la modificación y a mí me coge los datos
> > El 26/5/2015 17:33, "Juan Julián Merelo Guervós" <
> notifications@github.com>
> > escribió:
> >
> >> @iblancasa <https://github.com/iblancasa> usan el header "nosniff"
> >> https://github.com/blog/1482- ¿No se podría poner como estaba al
> >> principio? Por lo pronto lo resuelvo así. ¿Puedes hacer una rama en el
> app
> >> que ponga la dirección como quieras?
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <
> https://github.com/elecciones-ugr/elecciones-ugr.github.io/issues/6#issuecomment-105569366
> >
>
> >> .
> >>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elecciones-ugr/elecciones-ugr.github.io/issues/6#issuecomment-105575042>
> .
>



-- 
Manu

**Comment by iblancasa** [comment]
Sí.
Gruntfile no mola...

**Comment by Makova** [comment]
@JJ ¿Cómo ejecutas el script en otros navegadores, te refieres al scraper? es por probarlo yo también en Chrome y Chromium.
El index.html si se ve bien.

**Comment by JJ** [comment]
No, es la web directamente. El scraper está en Perl, para línea de órdenes.

El 26 de mayo de 2015, 18:22, Manu <notifications@github.com> escribió:

> @JJ <https://github.com/JJ> ¿Cómo ejecutas el script en otros
> navegadores, te refieres al scraper? es por probarlo yo también en Chrome y
> Chromium.
> El index.html si se ve bien.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elecciones-ugr/elecciones-ugr.github.io/issues/6#issuecomment-105587527>
> .
>



-- 
JJ

**Comment by Makova** [comment]
Si es esta http://elecciones-ugr.github.io/ yo la veo bien todos los
navegadores, Firefox, Chromium y Chrome.

El 26 de mayo de 2015, 18:24, Juan Julián Merelo Guervós <
notifications@github.com> escribió:

> No, es la web directamente. El scraper está en Perl, para línea de órdenes.
>
> El 26 de mayo de 2015, 18:22, Manu <notifications@github.com> escribió:
>
> > @JJ <https://github.com/JJ> ¿Cómo ejecutas el script en otros
> > navegadores, te refieres al scraper? es por probarlo yo también en
> Chrome y
> > Chromium.
> > El index.html si se ve bien.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/elecciones-ugr/elecciones-ugr.github.io/issues/6#issuecomment-105587527
> >
> > .
> >
>
>
>
> --
> JJ
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elecciones-ugr/elecciones-ugr.github.io/issues/6#issuecomment-105588967>
> .
>



-- 
Manu

**Comment by JJ** [comment]
Ahora sí, la he puesto como estaba.

El 26 de mayo de 2015, 18:28, Manu <notifications@github.com> escribió:

> Si es esta http://elecciones-ugr.github.io/ yo la veo bien todos los
> navegadores, Firefox, Chromium y Chrome.
>
> El 26 de mayo de 2015, 18:24, Juan Julián Merelo Guervós <
> notifications@github.com> escribió:
>
> > No, es la web directamente. El scraper está en Perl, para línea de
> órdenes.
> >
> > El 26 de mayo de 2015, 18:22, Manu <notifications@github.com> escribió:
> >
> > > @JJ <https://github.com/JJ> ¿Cómo ejecutas el script en otros
> > > navegadores, te refieres al scraper? es por probarlo yo también en
> > Chrome y
> > > Chromium.
> > > El index.html si se ve bien.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/elecciones-ugr/elecciones-ugr.github.io/issues/6#issuecomment-105587527
> > >
> > > .
> > >
> >
> >
> >
> > --
> > JJ
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/elecciones-ugr/elecciones-ugr.github.io/issues/6#issuecomment-105588967
> >
> > .
> >
>
>
>
> --
> Manu
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elecciones-ugr/elecciones-ugr.github.io/issues/6#issuecomment-105592516>
> .
>



-- 
JJ

**Comment by Makova** [comment]
Pues compilo de nuevo la apk a ver como queda.

El 26 de mayo de 2015, 18:30, Juan Julián Merelo Guervós <
notifications@github.com> escribió:

> Ahora sí, la he puesto como estaba.
>
>
> El 26 de mayo de 2015, 18:28, Manu <notifications@github.com> escribió:
>
> > Si es esta http://elecciones-ugr.github.io/ yo la veo bien todos los
> > navegadores, Firefox, Chromium y Chrome.
> >
> > El 26 de mayo de 2015, 18:24, Juan Julián Merelo Guervós <
> > notifications@github.com> escribió:
> >
> > > No, es la web directamente. El scraper está en Perl, para línea de
> > órdenes.
> > >
> > > El 26 de mayo de 2015, 18:22, Manu <notifications@github.com>
> escribió:
> > >
> > > > @JJ <https://github.com/JJ> ¿Cómo ejecutas el script en otros
> > > > navegadores, te refieres al scraper? es por probarlo yo también en
> > > Chrome y
> > > > Chromium.
> > > > El index.html si se ve bien.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/elecciones-ugr/elecciones-ugr.github.io/issues/6#issuecomment-105587527
> > > >
> > > > .
> > > >
> > >
> > >
> > >
> > > --
> > > JJ
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/elecciones-ugr/elecciones-ugr.github.io/issues/6#issuecomment-105588967
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Manu
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/elecciones-ugr/elecciones-ugr.github.io/issues/6#issuecomment-105592516
> >
> > .
> >
>
>
>
> --
> JJ
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elecciones-ugr/elecciones-ugr.github.io/issues/6#issuecomment-105593219>
> .
>



-- 
Manu

**Comment by Makova** [comment]
Ya he compilado con los últimos cambios de logos, colores, url. Funciona todo bien, menos descargar en hoja de cálculo (CSV)

![eleccionesugr](https://cloud.githubusercontent.com/assets/3070918/7818242/bb961812-03da-11e5-8837-6314b946e689.png)
![eleccionesugr1](https://cloud.githubusercontent.com/assets/3070918/7818243/bb9f812c-03da-11e5-8397-3951033d20b0.png)
![eleccionesugr2](https://cloud.githubusercontent.com/assets/3070918/7818244/bba1237e-03da-11e5-9a67-a9bd44e92002.png)

**Comment by Makova** [comment]
Subida en Release como `eleccionesUGR2015-2.apk`

**Comment by iblancasa** [comment]
El resultados.jsonp está insertado tal que src="resultados.jsonp" en la app
¿verdad? Por que así no se van a actualizar los datos del sondeo....
Podríamos probar a cambiarlo poniendo la url de la página, es decir,
http://elecciones-ugr.github.io/resultados.jsonp ya que donde parece que da
el problema es si cogemos el JSONP de GitHub (pero no sabemos si al ser una
página...)

**Comment by Makova** [comment]
En resultados.jsonp solo hay resultados. Pero creo que se a que te refieres
y puede ser que no actualice los datos. Descarga la apk que he subido en
Release y mira ver si te actualiza. Pero siempre veo los mismos porcentajes
31.76% desde el panatallazo que subiste tú al Release.

El 26 de mayo de 2015, 19:15, Israel Blancas <notifications@github.com>
escribió:

> El resultados.jsonp está insertado tal que src="resultados.jsonp" en la app
> ¿verdad? Por que así no se van a actualizar los datos del sondeo....
> Podríamos probar a cambiarlo poniendo la url de la página, es decir,
> http://elecciones-ugr.github.io/resultados.jsonp ya que donde parece que
> da
> el problema es si cogemos el JSONP de GitHub (pero no sabemos si al ser una
> página...)
> El 26/5/2015 19:09, "Manu" <notifications@github.com> escribió:
>
> > Ya he compilado con los últimos cambios de logos, colores, url. Funciona
> > todo bien, menos descargar en hoja de cálculo (CSV)
> >
> > [image: eleccionesugr]
> > <
> https://cloud.githubusercontent.com/assets/3070918/7818242/bb961812-03da-11e5-8837-6314b946e689.png
> >
> > [image: eleccionesugr1]
> > <
> https://cloud.githubusercontent.com/assets/3070918/7818243/bb9f812c-03da-11e5-8397-3951033d20b0.png
> >
> > [image: eleccionesugr2]
> > <
> https://cloud.githubusercontent.com/assets/3070918/7818244/bba1237e-03da-11e5-9a67-a9bd44e92002.png
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/elecciones-ugr/elecciones-ugr.github.io/issues/6#issuecomment-105605385
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elecciones-ugr/elecciones-ugr.github.io/issues/6#issuecomment-105608052>
> .
>



-- 
Manu

**Comment by iblancasa** [comment]
Sí.
Siempre se ven los mismos datos por que no los hemos cambiado... Pero el
día del escrutinio supongo que el resultados.jsonp que hay en GitHub irá
cambiando.
En la app se está leyendo un resultados local... Lo que hace falta es que
lea el del repo... Por eso digo que probemos con el de la web de
elecciones.....github.io . Cogiendo el del repo directamente le da
problemas a JJ... Pero el de la web tal vez no (por ser web). Ese será el
que hay que ir cambiando cuando se haga el escrutinio

**Comment by Makova** [comment]
Pues podríamos probarlo ya. A parte de que habría que hacer alguna prueba
con datos reales de lo que sea, vaya que mañana no funcione.

--
Makova

**Comment by JJ** [comment]
Hola,

El 26 de mayo de 2015, 19:39, Israel Blancas <notifications@github.com>
escribió:

> Sí.
> Siempre se ven los mismos datos por que no los hemos cambiado... Pero el
> día del escrutinio supongo que el resultados.jsonp que hay en GitHub irá
> cambiando.
>

Efectivamente. Si queréis se puede hacer una rama con esa variación, no
cuesta ningún trabajo.


> En la app se está leyendo un resultados local... Lo que hace falta es que
> lea el del repo... Por eso digo que probemos con el de la web de
> elecciones.....github.io . Cogiendo el del repo directamente le da
> problemas a JJ... Pero el de la web tal vez no (por ser web). Ese será el
> que hay que ir cambiando cuando se haga el escrutinio


Cuesta menos trabajo una rama con una línea cambiada. ¡O un gruntfile!

**Comment by iblancasa** [comment]
Que no se hacer gruntfiles :(

**Comment by Makova** [comment]
Pues anda que yo.

**Comment by iblancasa** [comment]
Hola:

Israel te ha invitado a unirte a la Copa universitaria de Dropbox. La Copa universitaria te permite unirte a tus compañeros para conseguir hasta 25 GB de espacio de Dropbox gratis durante dos años.

Para conseguir espacio, solo tienes que invitar a amigos y utilizar Dropbox para compartir, colaborar y trabajar.

¡Únete a la Copa universitaria![2]

Ten en cuenta que, para participar, debes ser un alumno inscrito actualmente en un centro de enseñanza superior. Más información acerca de la Copa universitaria[3]

¡Disfruta de Dropbox!


 
 Trabaja en equipo, gana en equipo.

____________________________________________________
Si prefieres no recibir invitaciones de Dropbox, visita este enlace[4].
Dropbox, Inc., PO Box 77767, San Francisco, California 94107

[1]: https://www.dropbox.com/l/QsmHJ943nJKWSZ5OgtXSQG/campuscup?text=1
[2]: https://www.dropbox.com/l/O9ezEelXcUWox2V5K2TKgr/campuscup?text=1
[3]: https://www.dropbox.com/l/dMq7TaJ5KygDRyPJtPQGtj/help/9131?text=1
[4]: https://www.dropbox.com/l/bWg0wyBkxwQadw0s0gVO3z?text=1
