### ISSUE TITLE
En el Firefox no funcionan los enlaces dentro de botones

### ISSUE THREAD

**Issue by germaaan** [elecciones-ugr/elecciones-ugr.github.io#7]
Los enlaces a la página de la OSL y del repo con los fuentes de la web dentro del botón en el fondo de la página no funcionan en Firefox, pero en Chrome si funcionan perfectamente, supongo que será una incompatibilidad de Kube con Firefox.

**Comment by Makova** [comment]
A mi sie funcionan, lo que no cambian es de color al clicarles.

**Comment by Makova** [comment]
Pues no, no van los enlaces. Hasta hace nada me funcionaban.

**Comment by JJ** [comment]
Voy a ver qué pasa.

El 27 de mayo de 2015, 11:14, Manu <notifications@github.com> escribió:

> Pues no, no van los enlaces. Hasta hace nada me funcionaban.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elecciones-ugr/elecciones-ugr.github.io/issues/7#issuecomment-105834136>
> .
>



-- 
JJ
